// ADR 018 picks a force-directed layout but leaves the rendering
// library/output format open. This renders GIF frames with the standard
// library (image/gif) as a simple default, not a locked-in choice.
package chronicle

import (
	"encoding/csv"
	"errors"
	"fmt"
	"image"
	"image/color"
	"image/gif"
	"io"
	"log"
	"math"
	"math/rand/v2"
	"os"
	"sort"
	"time"
)

type growthRow struct {
	createdAt time.Time
	nodeID    string
	parentID  string
}

type point struct {
	x, y   float64
	vx, vy float64
}

const (
	canvasSize        = 400
	relaxIterations   = 30
	repulsionStrength = 2000.0
	springStrength    = 0.02
	springLength      = 60.0
	damping           = 0.85
)

// readGrowthCSV skips malformed rows (bad timestamp, wrong field count)
// rather than failing the whole file: this CSV is self-generated by our own
// export step (SRS 012), not untrusted input, so a bad row is almost always
// a bug in the exporter — the point of skipping is to keep building the
// graph from the rows that ARE good, not to silently hide the problem, so
// every skipped row is logged (visible, not silent) to whoever runs this tool.
func readGrowthCSV(path string) ([]growthRow, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	r := csv.NewReader(f)
	r.FieldsPerRecord = -1 // rows may have a different field count; checked per-row below

	header, err := r.Read()
	if err != nil {
		return nil, fmt.Errorf("chronicle: read CSV header: %w", err)
	}
	_ = header

	var rows []growthRow
	lineNum := 1 // header was line 1
	for {
		lineNum++
		rec, err := r.Read()
		if errors.Is(err, io.EOF) {
			break
		}
		if err != nil {
			log.Printf("chronicle: growth CSV %s: skipping malformed line %d: %v", path, lineNum, err)
			continue
		}
		if len(rec) < 3 {
			log.Printf("chronicle: growth CSV %s: skipping line %d: got %d fields, want >= 3", path, lineNum, len(rec))
			continue
		}
		t, err := time.Parse(time.RFC3339, rec[0])
		if err != nil {
			log.Printf("chronicle: growth CSV %s: skipping line %d: bad timestamp %q: %v", path, lineNum, rec[0], err)
			continue
		}
		rows = append(rows, growthRow{createdAt: t, nodeID: rec[1], parentID: rec[2]})
	}
	if len(rows) == 0 {
		return nil, fmt.Errorf("chronicle: no usable rows in %s", path)
	}
	sort.Slice(rows, func(i, j int) bool { return rows[i].createdAt.Before(rows[j].createdAt) })
	return rows, nil
}

// RenderGrowthVideo reads a growth CSV and writes an animated GIF: nodes
// appear in creation order, linked to their parent, laid out with a basic
// force-directed relaxation.
func RenderGrowthVideo(csvPath, outPath string) error {
	rows, err := readGrowthCSV(csvPath)
	if err != nil {
		return err
	}

	points := make(map[string]*point)
	order := []string{}
	palette := color.Palette{color.White, color.Black, color.RGBA{160, 160, 160, 255}}

	anim := &gif.GIF{}

	for _, row := range rows {
		if _, exists := points[row.nodeID]; exists {
			continue
		}
		px, py := canvasSize/2+rand.Float64()*20-10, canvasSize/2+rand.Float64()*20-10
		if parent, ok := points[row.parentID]; ok {
			px = parent.x + rand.Float64()*20 - 10
			py = parent.y + rand.Float64()*20 - 10
		}
		points[row.nodeID] = &point{x: px, y: py}
		order = append(order, row.nodeID)

		for range relaxIterations {
			relax(points, order, rows)
		}
		anim.Image = append(anim.Image, renderFrame(points, order, rows, palette))
		anim.Delay = append(anim.Delay, 20)
	}

	f, err := os.Create(outPath)
	if err != nil {
		return err
	}
	defer f.Close()
	return gif.EncodeAll(f, anim)
}

func relax(points map[string]*point, order []string, rows []growthRow) {
	forces := make(map[string][2]float64, len(order))

	for i, a := range order {
		for _, b := range order[i+1:] {
			pa, pb := points[a], points[b]
			dx, dy := pa.x-pb.x, pa.y-pb.y
			distSq := dx*dx + dy*dy + 0.01
			f := repulsionStrength / distSq
			dist := math.Sqrt(distSq)
			fx, fy := f*dx/dist, f*dy/dist
			forces[a] = add(forces[a], fx, fy)
			forces[b] = add(forces[b], -fx, -fy)
		}
	}

	for _, row := range rows {
		if row.parentID == "" {
			continue
		}
		pa, okA := points[row.nodeID]
		pb, okB := points[row.parentID]
		if !okA || !okB {
			continue
		}
		dx, dy := pa.x-pb.x, pa.y-pb.y
		dist := math.Sqrt(dx*dx + dy*dy + 0.01)
		stretch := dist - springLength
		fx, fy := -springStrength*stretch*dx/dist, -springStrength*stretch*dy/dist
		forces[row.nodeID] = add(forces[row.nodeID], fx, fy)
		forces[row.parentID] = add(forces[row.parentID], -fx, -fy)
	}

	for _, id := range order {
		p := points[id]
		f := forces[id]
		p.vx = (p.vx + f[0]) * damping
		p.vy = (p.vy + f[1]) * damping
		p.x = clamp(p.x+p.vx, 10, canvasSize-10)
		p.y = clamp(p.y+p.vy, 10, canvasSize-10)
	}
}

func renderFrame(points map[string]*point, order []string, rows []growthRow, palette color.Palette) *image.Paletted {
	img := image.NewPaletted(image.Rect(0, 0, canvasSize, canvasSize), palette)
	for y := range canvasSize {
		for x := range canvasSize {
			img.SetColorIndex(x, y, 0)
		}
	}
	for _, row := range rows {
		pa, okA := points[row.nodeID]
		pb, okB := points[row.parentID]
		if row.parentID == "" || !okA || !okB {
			continue
		}
		drawLine(img, int(pa.x), int(pa.y), int(pb.x), int(pb.y), 2)
	}
	for _, id := range order {
		p := points[id]
		drawCircle(img, int(p.x), int(p.y), 3, 1)
	}
	return img
}

func drawCircle(img *image.Paletted, cx, cy, r int, colorIndex uint8) {
	for dy := -r; dy <= r; dy++ {
		for dx := -r; dx <= r; dx++ {
			if dx*dx+dy*dy <= r*r {
				setSafe(img, cx+dx, cy+dy, colorIndex)
			}
		}
	}
}

func drawLine(img *image.Paletted, x0, y0, x1, y1 int, colorIndex uint8) {
	dx, dy := abs(x1-x0), -abs(y1-y0)
	sx, sy := sign(x1-x0), sign(y1-y0)
	err := dx + dy
	for {
		setSafe(img, x0, y0, colorIndex)
		if x0 == x1 && y0 == y1 {
			break
		}
		e2 := 2 * err
		if e2 >= dy {
			err += dy
			x0 += sx
		}
		if e2 <= dx {
			err += dx
			y0 += sy
		}
	}
}

func setSafe(img *image.Paletted, x, y int, colorIndex uint8) {
	if x >= 0 && x < canvasSize && y >= 0 && y < canvasSize {
		img.SetColorIndex(x, y, colorIndex)
	}
}

func add(v [2]float64, x, y float64) [2]float64 { return [2]float64{v[0] + x, v[1] + y} }
func clamp(v, lo, hi float64) float64 {
	if v < lo {
		return lo
	}
	if v > hi {
		return hi
	}
	return v
}
func abs(v int) int {
	if v < 0 {
		return -v
	}
	return v
}
func sign(v int) int {
	if v < 0 {
		return -1
	}
	if v > 0 {
		return 1
	}
	return 0
}
