// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.1
// source: spore.proto

package sporepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NodeService_SubmitData_FullMethodName      = "/spore.NodeService/SubmitData"
	NodeService_SubmitTerminate_FullMethodName = "/spore.NodeService/SubmitTerminate"
	NodeService_Ping_FullMethodName            = "/spore.NodeService/Ping"
	NodeService_PingIndirect_FullMethodName    = "/spore.NodeService/PingIndirect"
	NodeService_GossipRound_FullMethodName     = "/spore.NodeService/GossipRound"
	NodeService_MerkleChildren_FullMethodName  = "/spore.NodeService/MerkleChildren"
	NodeService_MerkleLeaf_FullMethodName      = "/spore.NodeService/MerkleLeaf"
	NodeService_GetObjects_FullMethodName      = "/spore.NodeService/GetObjects"
)

// NodeServiceClient is the client API for NodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodeServiceClient interface {
	SubmitData(ctx context.Context, in *SubmitDataRequest, opts ...grpc.CallOption) (*SubmitAck, error)
	SubmitTerminate(ctx context.Context, in *TerminateRequest, opts ...grpc.CallOption) (*TerminateAck, error)
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	PingIndirect(ctx context.Context, in *IndirectPingRequest, opts ...grpc.CallOption) (*IndirectPingResponse, error)
	GossipRound(ctx context.Context, in *GossipExchange, opts ...grpc.CallOption) (*GossipExchange, error)
	MerkleChildren(ctx context.Context, in *MerkleChildrenRequest, opts ...grpc.CallOption) (*MerkleChildrenResponse, error)
	MerkleLeaf(ctx context.Context, in *MerkleLeafRequest, opts ...grpc.CallOption) (*MerkleLeafResponse, error)
	GetObjects(ctx context.Context, in *GetObjectsRequest, opts ...grpc.CallOption) (*GetObjectsResponse, error)
}

type nodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeServiceClient(cc grpc.ClientConnInterface) NodeServiceClient {
	return &nodeServiceClient{cc}
}

func (c *nodeServiceClient) SubmitData(ctx context.Context, in *SubmitDataRequest, opts ...grpc.CallOption) (*SubmitAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitAck)
	err := c.cc.Invoke(ctx, NodeService_SubmitData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) SubmitTerminate(ctx context.Context, in *TerminateRequest, opts ...grpc.CallOption) (*TerminateAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TerminateAck)
	err := c.cc.Invoke(ctx, NodeService_SubmitTerminate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, NodeService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) PingIndirect(ctx context.Context, in *IndirectPingRequest, opts ...grpc.CallOption) (*IndirectPingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IndirectPingResponse)
	err := c.cc.Invoke(ctx, NodeService_PingIndirect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) GossipRound(ctx context.Context, in *GossipExchange, opts ...grpc.CallOption) (*GossipExchange, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GossipExchange)
	err := c.cc.Invoke(ctx, NodeService_GossipRound_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) MerkleChildren(ctx context.Context, in *MerkleChildrenRequest, opts ...grpc.CallOption) (*MerkleChildrenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MerkleChildrenResponse)
	err := c.cc.Invoke(ctx, NodeService_MerkleChildren_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) MerkleLeaf(ctx context.Context, in *MerkleLeafRequest, opts ...grpc.CallOption) (*MerkleLeafResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MerkleLeafResponse)
	err := c.cc.Invoke(ctx, NodeService_MerkleLeaf_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) GetObjects(ctx context.Context, in *GetObjectsRequest, opts ...grpc.CallOption) (*GetObjectsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetObjectsResponse)
	err := c.cc.Invoke(ctx, NodeService_GetObjects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeServiceServer is the server API for NodeService service.
// All implementations must embed UnimplementedNodeServiceServer
// for forward compatibility.
type NodeServiceServer interface {
	SubmitData(context.Context, *SubmitDataRequest) (*SubmitAck, error)
	SubmitTerminate(context.Context, *TerminateRequest) (*TerminateAck, error)
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	PingIndirect(context.Context, *IndirectPingRequest) (*IndirectPingResponse, error)
	GossipRound(context.Context, *GossipExchange) (*GossipExchange, error)
	MerkleChildren(context.Context, *MerkleChildrenRequest) (*MerkleChildrenResponse, error)
	MerkleLeaf(context.Context, *MerkleLeafRequest) (*MerkleLeafResponse, error)
	GetObjects(context.Context, *GetObjectsRequest) (*GetObjectsResponse, error)
	mustEmbedUnimplementedNodeServiceServer()
}

// UnimplementedNodeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeServiceServer struct{}

func (UnimplementedNodeServiceServer) SubmitData(context.Context, *SubmitDataRequest) (*SubmitAck, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitData not implemented")
}
func (UnimplementedNodeServiceServer) SubmitTerminate(context.Context, *TerminateRequest) (*TerminateAck, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitTerminate not implemented")
}
func (UnimplementedNodeServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedNodeServiceServer) PingIndirect(context.Context, *IndirectPingRequest) (*IndirectPingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PingIndirect not implemented")
}
func (UnimplementedNodeServiceServer) GossipRound(context.Context, *GossipExchange) (*GossipExchange, error) {
	return nil, status.Error(codes.Unimplemented, "method GossipRound not implemented")
}
func (UnimplementedNodeServiceServer) MerkleChildren(context.Context, *MerkleChildrenRequest) (*MerkleChildrenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MerkleChildren not implemented")
}
func (UnimplementedNodeServiceServer) MerkleLeaf(context.Context, *MerkleLeafRequest) (*MerkleLeafResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MerkleLeaf not implemented")
}
func (UnimplementedNodeServiceServer) GetObjects(context.Context, *GetObjectsRequest) (*GetObjectsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetObjects not implemented")
}
func (UnimplementedNodeServiceServer) mustEmbedUnimplementedNodeServiceServer() {}
func (UnimplementedNodeServiceServer) testEmbeddedByValue()                     {}

// UnsafeNodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeServiceServer will
// result in compilation errors.
type UnsafeNodeServiceServer interface {
	mustEmbedUnimplementedNodeServiceServer()
}

func RegisterNodeServiceServer(s grpc.ServiceRegistrar, srv NodeServiceServer) {
	// If the following call panics, it indicates UnimplementedNodeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeService_ServiceDesc, srv)
}

func _NodeService_SubmitData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).SubmitData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_SubmitData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).SubmitData(ctx, req.(*SubmitDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_SubmitTerminate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TerminateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).SubmitTerminate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_SubmitTerminate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).SubmitTerminate(ctx, req.(*TerminateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_PingIndirect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IndirectPingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).PingIndirect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_PingIndirect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).PingIndirect(ctx, req.(*IndirectPingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_GossipRound_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GossipExchange)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).GossipRound(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_GossipRound_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).GossipRound(ctx, req.(*GossipExchange))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_MerkleChildren_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MerkleChildrenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).MerkleChildren(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_MerkleChildren_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).MerkleChildren(ctx, req.(*MerkleChildrenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_MerkleLeaf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MerkleLeafRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).MerkleLeaf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_MerkleLeaf_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).MerkleLeaf(ctx, req.(*MerkleLeafRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_GetObjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetObjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).GetObjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_GetObjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).GetObjects(ctx, req.(*GetObjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NodeService_ServiceDesc is the grpc.ServiceDesc for NodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "spore.NodeService",
	HandlerType: (*NodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitData",
			Handler:    _NodeService_SubmitData_Handler,
		},
		{
			MethodName: "SubmitTerminate",
			Handler:    _NodeService_SubmitTerminate_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _NodeService_Ping_Handler,
		},
		{
			MethodName: "PingIndirect",
			Handler:    _NodeService_PingIndirect_Handler,
		},
		{
			MethodName: "GossipRound",
			Handler:    _NodeService_GossipRound_Handler,
		},
		{
			MethodName: "MerkleChildren",
			Handler:    _NodeService_MerkleChildren_Handler,
		},
		{
			MethodName: "MerkleLeaf",
			Handler:    _NodeService_MerkleLeaf_Handler,
		},
		{
			MethodName: "GetObjects",
			Handler:    _NodeService_GetObjects_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "spore.proto",
}
