// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.1
// source: spore.proto

package sporepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SpawnMode int32

const (
	SpawnMode_PROCESS SpawnMode = 0 // implemented in v0
	SpawnMode_DOCKER  SpawnMode = 1 // reserved, not implemented
)

// Enum value maps for SpawnMode.
var (
	SpawnMode_name = map[int32]string{
		0: "PROCESS",
		1: "DOCKER",
	}
	SpawnMode_value = map[string]int32{
		"PROCESS": 0,
		"DOCKER":  1,
	}
)

func (x SpawnMode) Enum() *SpawnMode {
	p := new(SpawnMode)
	*p = x
	return p
}

func (x SpawnMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SpawnMode) Descriptor() protoreflect.EnumDescriptor {
	return file_spore_proto_enumTypes[0].Descriptor()
}

func (SpawnMode) Type() protoreflect.EnumType {
	return &file_spore_proto_enumTypes[0]
}

func (x SpawnMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SpawnMode.Descriptor instead.
func (SpawnMode) EnumDescriptor() ([]byte, []int) {
	return file_spore_proto_rawDescGZIP(), []int{0}
}

type DataType int32

const (
	DataType_FILE    DataType = 0
	DataType_COMMAND DataType = 1
)

// Enum value maps for DataType.
var (
	DataType_name = map[int32]string{
		0: "FILE",
		1: "COMMAND",
	}
	DataType_value = map[string]int32{
		"FILE":    0,
		"COMMAND": 1,
	}
)

func (x DataType) Enum() *DataType {
	p := new(DataType)
	*p = x
	return p
}

func (x DataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataType) Descriptor() protoreflect.EnumDescriptor {
	return file_spore_proto_enumTypes[1].Descriptor()
}

func (DataType) Type() protoreflect.EnumType {
	return &file_spore_proto_enumTypes[1]
}

func (x DataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataType.Descriptor instead.
func (DataType) EnumDescriptor() ([]byte, []int) {
	return file_spore_proto_rawDescGZIP(), []int{1}
}

type MemberStatus int32

const (
	MemberStatus_ALIVE   MemberStatus = 0
	MemberStatus_SUSPECT MemberStatus = 1
	MemberStatus_DEAD    MemberStatus = 2
)

// Enum value maps for MemberStatus.
var (
	MemberStatus_name = map[int32]string{
		0: "ALIVE",
		1: "SUSPECT",
		2: "DEAD",
	}
	MemberStatus_value = map[string]int32{
		"ALIVE":   0,
		"SUSPECT": 1,
		"DEAD":    2,
	}
)

func (x MemberStatus) Enum() *MemberStatus {
	p := new(MemberStatus)
	*p = x
	return p
}

func (x MemberStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MemberStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_spore_proto_enumTypes[2].Descriptor()
}

func (MemberStatus) Type() protoreflect.EnumType {
	return &file_spore_proto_enumTypes[2]
}

func (x MemberStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MemberStatus.Descriptor instead.
func (MemberStatus) EnumDescriptor() ([]byte, []int) {
	return file_spore_proto_rawDescGZIP(), []int{2}
}

type TreeKind int32

const (
	TreeKind_DATA    TreeKind = 0
	TreeKind_METRICS TreeKind = 1
)

// Enum value maps for TreeKind.
var (
	TreeKind_name = map[int32]string{
		0: "DATA",
		1: "METRICS",
	}
	TreeKind_value = map[string]int32{
		"DATA":    0,
		"METRICS": 1,
	}
)

func (x TreeKind) Enum() *TreeKind {
	p := new(TreeKind)
	*p = x
	return p
}

func (x TreeKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TreeKind) Descriptor() protoreflect.EnumDescriptor {
	return file_spore_proto_enumTypes[3].Descriptor()
}

func (TreeKind) Type() protoreflect.EnumType {
	return &file_spore_proto_enumTypes[3]
}

func (x TreeKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TreeKind.Descriptor instead.
func (TreeKind) EnumDescriptor() ([]byte, []int) {
	return file_spore_proto_rawDescGZIP(), []int{3}
}

type SpawnRules struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	MaxGenerationDepth   int32                  `protobuf:"varint,1,opt,name=max_generation_depth,json=maxGenerationDepth,proto3" json:"max_generation_depth,omitempty"`
	SpawnIntervalSeconds int32                  `protobuf:"varint,2,opt,name=spawn_interval_seconds,json=spawnIntervalSeconds,proto3" json:"spawn_interval_seconds,omitempty"`
	SpawnMode            SpawnMode              `protobuf:"varint,3,opt,name=spawn_mode,json=spawnMode,proto3,enum=spore.SpawnMode" json:"spawn_mode,omitempty"`
	MaxChildrenPerBatch  int32                  `protobuf:"varint,4,opt,name=max_children_per_batch,json=maxChildrenPerBatch,proto3" json:"max_children_per_batch,omitempty"` // 0 = default (5)
	BatchPauseSeconds    int32                  `protobuf:"varint,5,opt,name=batch_pause_seconds,json=batchPauseSeconds,proto3" json:"batch_pause_seconds,omitempty"`         // 0 = default (900 = 15 min)
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SpawnRules) Reset() {
	*x = SpawnRules{}
	mi := &file_spore_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpawnRules) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpawnRules) ProtoMessage() {}

func (x *SpawnRules) ProtoReflect() protoreflect.Message {
	mi := &file_spore_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpawnRules.ProtoReflect.Descriptor instead.
func (*SpawnRules) Descriptor() ([]byte, []int) {
	return file_spore_proto_rawDescGZIP(), []int{0}
}

func (x *SpawnRules) GetMaxGenerationDepth() int32 {
	if x != nil {
		return x.MaxGenerationDepth
	}
	return 0
}

func (x *SpawnRules) GetSpawnIntervalSeconds() int32 {
	if x != nil {
		return x.SpawnIntervalSeconds
	}
	return 0
}

func (x *SpawnRules) GetSpawnMode() SpawnMode {
	if x != nil {
		return x.SpawnMode
	}
	return SpawnMode_PROCESS
}

func (x *SpawnRules) GetMaxChildrenPerBatch() int32 {
	if x != nil {
		return x.MaxChildrenPerBatch
	}
	return 0
}

func (x *SpawnRules) GetBatchPauseSeconds() int32 {
	if x != nil {
		return x.BatchPauseSeconds
	}
	return 0
}

type Genesis struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	NetworkId                  string                 `protobuf:"bytes,1,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	OwnerPublicKey             []byte                 `protobuf:"bytes,2,opt,name=owner_public_key,json=ownerPublicKey,proto3" json:"owner_public_key,omitempty"`                                       // Ed25519
	MetricsEncryptionPublicKey []byte                 `protobuf:"bytes,3,opt,name=metrics_encryption_public_key,json=metricsEncryptionPublicKey,proto3" json:"metrics_encryption_public_key,omitempty"` // X25519
	SpawnRules                 *SpawnRules            `protobuf:"bytes,4,opt,name=spawn_rules,json=spawnRules,proto3" json:"spawn_rules,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *Genesis) Reset() {
	*x = Genesis{}
	mi := &file_spore_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Genesis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Genesis) ProtoMessage() {}

func (x *Genesis) ProtoReflect() protoreflect.Message {
	mi := &file_spore_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Genesis.ProtoReflect.Descriptor instead.
func (*Genesis) Descriptor() ([]byte, []int) {
	return file_spore_proto_rawDescGZIP(), []int{1}
}

func (x *Genesis) GetNetworkId() string {
	if x != nil {
		return x.NetworkId
	}
	return ""
}

func (x *Genesis) GetOwnerPublicKey() []byte {
	if x != nil {
		return x.OwnerPublicKey
	}
	return nil
}

func (x *Genesis) GetMetricsEncryptionPublicKey() []byte {
	if x != nil {
		return x.MetricsEncryptionPublicKey
	}
	return nil
}

func (x *Genesis) GetSpawnRules() *SpawnRules {
	if x != nil {
		return x.SpawnRules
	}
	return nil
}

type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BashCommand   string                 `protobuf:"bytes,1,opt,name=bash_command,json=bashCommand,proto3" json:"bash_command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_spore_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_spore_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_spore_proto_rawDescGZIP(), []int{2}
}

func (x *Command) GetBashCommand() string {
	if x != nil {
		return x.BashCommand
	}
	return ""
}

type SubmitDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          DataType               `protobuf:"varint,1,opt,name=type,proto3,enum=spore.DataType" json:"type,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Signature     []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"` // owner's Ed25519 signature over content
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitDataRequest) Reset() {
	*x = SubmitDataRequest{}
	mi := &file_spore_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitDataRequest) ProtoMessage() {}

func (x *SubmitDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spore_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitDataRequest.ProtoReflect.Descriptor instead.
func (*SubmitDataRequest) Descriptor() ([]byte, []int) {
	return file_spore_proto_rawDescGZIP(), []int{3}
}

func (x *SubmitDataRequest) GetType() DataType {
	if x != nil {
		return x.Type
	}
	return DataType_FILE
}

func (x *SubmitDataRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *SubmitDataRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type SubmitAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	ObjectId      []byte                 `protobuf:"bytes,2,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"` // hash(content)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitAck) Reset() {
	*x = SubmitAck{}
	mi := &file_spore_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitAck) ProtoMessage() {}

func (x *SubmitAck) ProtoReflect() protoreflect.Message {
	mi := &file_spore_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitAck.ProtoReflect.Descriptor instead.
func (*SubmitAck) Descriptor() ([]byte, []int) {
	return file_spore_proto_rawDescGZIP(), []int{4}
}

func (x *SubmitAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *SubmitAck) GetObjectId() []byte {
	if x != nil {
		return x.ObjectId
	}
	return nil
}

type StoredObject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          DataType               `protobuf:"varint,1,opt,name=type,proto3,enum=spore.DataType" json:"type,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Signature     []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoredObject) Reset() {
	*x = StoredObject{}
	mi := &file_spore_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoredObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoredObject) ProtoMessage() {}

func (x *StoredObject) ProtoReflect() protoreflect.Message {
	mi := &file_spore_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoredObject.ProtoReflect.Descriptor instead.
func (*StoredObject) Descriptor() ([]byte, []int) {
	return file_spore_proto_rawDescGZIP(), []int{5}
}

func (x *StoredObject) GetType() DataType {
	if x != nil {
		return x.Type
	}
	return DataType_FILE
}

func (x *StoredObject) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *StoredObject) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type TerminateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signature     []byte                 `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"` // owner's signature over network_id + "TERMINATE"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminateRequest) Reset() {
	*x = TerminateRequest{}
	mi := &file_spore_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminateRequest) ProtoMessage() {}

func (x *TerminateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spore_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminateRequest.ProtoReflect.Descriptor instead.
func (*TerminateRequest) Descriptor() ([]byte, []int) {
	return file_spore_proto_rawDescGZIP(), []int{6}
}

func (x *TerminateRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type TerminateAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Received      bool                   `protobuf:"varint,1,opt,name=received,proto3" json:"received,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminateAck) Reset() {
	*x = TerminateAck{}
	mi := &file_spore_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminateAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminateAck) ProtoMessage() {}

func (x *TerminateAck) ProtoReflect() protoreflect.Message {
	mi := &file_spore_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminateAck.ProtoReflect.Descriptor instead.
func (*TerminateAck) Descriptor() ([]byte, []int) {
	return file_spore_proto_rawDescGZIP(), []int{7}
}

func (x *TerminateAck) GetReceived() bool {
	if x != nil {
		return x.Received
	}
	return false
}

type MemberState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Status        MemberStatus           `protobuf:"varint,2,opt,name=status,proto3,enum=spore.MemberStatus" json:"status,omitempty"`
	Incarnation   int64                  `protobuf:"varint,3,opt,name=incarnation,proto3" json:"incarnation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberState) Reset() {
	*x = MemberState{}
	mi := &file_spore_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberState) ProtoMessage() {}

func (x *MemberState) ProtoReflect() protoreflect.Message {
	mi := &file_spore_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberState.ProtoReflect.Descriptor instead.
func (*MemberState) Descriptor() ([]byte, []int) {
	return file_spore_proto_rawDescGZIP(), []int{8}
}

func (x *MemberState) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *MemberState) GetStatus() MemberStatus {
	if x != nil {
		return x.Status
	}
	return MemberStatus_ALIVE
}

func (x *MemberState) GetIncarnation() int64 {
	if x != nil {
		return x.Incarnation
	}
	return 0
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromAddress   string                 `protobuf:"bytes,1,opt,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty"`
	Piggyback     []*MemberState         `protobuf:"bytes,2,rep,name=piggyback,proto3" json:"piggyback,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_spore_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spore_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_spore_proto_rawDescGZIP(), []int{9}
}

func (x *PingRequest) GetFromAddress() string {
	if x != nil {
		return x.FromAddress
	}
	return ""
}

func (x *PingRequest) GetPiggyback() []*MemberState {
	if x != nil {
		return x.Piggyback
	}
	return nil
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Piggyback     []*MemberState         `protobuf:"bytes,2,rep,name=piggyback,proto3" json:"piggyback,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_spore_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spore_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_spore_proto_rawDescGZIP(), []int{10}
}

func (x *PingResponse) GetPiggyback() []*MemberState {
	if x != nil {
		return x.Piggyback
	}
	return nil
}

type IndirectPingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetAddress string                 `protobuf:"bytes,1,opt,name=target_address,json=targetAddress,proto3" json:"target_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndirectPingRequest) Reset() {
	*x = IndirectPingRequest{}
	mi := &file_spore_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndirectPingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndirectPingRequest) ProtoMessage() {}

func (x *IndirectPingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spore_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndirectPingRequest.ProtoReflect.Descriptor instead.
func (*IndirectPingRequest) Descriptor() ([]byte, []int) {
	return file_spore_proto_rawDescGZIP(), []int{11}
}

func (x *IndirectPingRequest) GetTargetAddress() string {
	if x != nil {
		return x.TargetAddress
	}
	return ""
}

type IndirectPingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acked         bool                   `protobuf:"varint,1,opt,name=acked,proto3" json:"acked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndirectPingResponse) Reset() {
	*x = IndirectPingResponse{}
	mi := &file_spore_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndirectPingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndirectPingResponse) ProtoMessage() {}

func (x *IndirectPingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spore_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndirectPingResponse.ProtoReflect.Descriptor instead.
func (*IndirectPingResponse) Descriptor() ([]byte, []int) {
	return file_spore_proto_rawDescGZIP(), []int{12}
}

func (x *IndirectPingResponse) GetAcked() bool {
	if x != nil {
		return x.Acked
	}
	return false
}

type GossipExchange struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DataRootHash    []byte                 `protobuf:"bytes,1,opt,name=data_root_hash,json=dataRootHash,proto3" json:"data_root_hash,omitempty"`
	MetricsRootHash []byte                 `protobuf:"bytes,2,opt,name=metrics_root_hash,json=metricsRootHash,proto3" json:"metrics_root_hash,omitempty"`
	KnownPeers      []string               `protobuf:"bytes,3,rep,name=known_peers,json=knownPeers,proto3" json:"known_peers,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GossipExchange) Reset() {
	*x = GossipExchange{}
	mi := &file_spore_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipExchange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipExchange) ProtoMessage() {}

func (x *GossipExchange) ProtoReflect() protoreflect.Message {
	mi := &file_spore_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipExchange.ProtoReflect.Descriptor instead.
func (*GossipExchange) Descriptor() ([]byte, []int) {
	return file_spore_proto_rawDescGZIP(), []int{13}
}

func (x *GossipExchange) GetDataRootHash() []byte {
	if x != nil {
		return x.DataRootHash
	}
	return nil
}

func (x *GossipExchange) GetMetricsRootHash() []byte {
	if x != nil {
		return x.MetricsRootHash
	}
	return nil
}

func (x *GossipExchange) GetKnownPeers() []string {
	if x != nil {
		return x.KnownPeers
	}
	return nil
}

// A tree node at fixed depth 8; the low `depth` bits of prefix_bits are
// meaningful.
type MerklePath struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Depth         uint32                 `protobuf:"varint,1,opt,name=depth,proto3" json:"depth,omitempty"`
	PrefixBits    uint32                 `protobuf:"varint,2,opt,name=prefix_bits,json=prefixBits,proto3" json:"prefix_bits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerklePath) Reset() {
	*x = MerklePath{}
	mi := &file_spore_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerklePath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerklePath) ProtoMessage() {}

func (x *MerklePath) ProtoReflect() protoreflect.Message {
	mi := &file_spore_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerklePath.ProtoReflect.Descriptor instead.
func (*MerklePath) Descriptor() ([]byte, []int) {
	return file_spore_proto_rawDescGZIP(), []int{14}
}

func (x *MerklePath) GetDepth() uint32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

func (x *MerklePath) GetPrefixBits() uint32 {
	if x != nil {
		return x.PrefixBits
	}
	return 0
}

type MerkleChildrenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tree          TreeKind               `protobuf:"varint,1,opt,name=tree,proto3,enum=spore.TreeKind" json:"tree,omitempty"`
	Paths         []*MerklePath          `protobuf:"bytes,2,rep,name=paths,proto3" json:"paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerkleChildrenRequest) Reset() {
	*x = MerkleChildrenRequest{}
	mi := &file_spore_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerkleChildrenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerkleChildrenRequest) ProtoMessage() {}

func (x *MerkleChildrenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spore_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerkleChildrenRequest.ProtoReflect.Descriptor instead.
func (*MerkleChildrenRequest) Descriptor() ([]byte, []int) {
	return file_spore_proto_rawDescGZIP(), []int{15}
}

func (x *MerkleChildrenRequest) GetTree() TreeKind {
	if x != nil {
		return x.Tree
	}
	return TreeKind_DATA
}

func (x *MerkleChildrenRequest) GetPaths() []*MerklePath {
	if x != nil {
		return x.Paths
	}
	return nil
}

type MerkleNodeHashes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeftHash      []byte                 `protobuf:"bytes,1,opt,name=left_hash,json=leftHash,proto3" json:"left_hash,omitempty"`
	RightHash     []byte                 `protobuf:"bytes,2,opt,name=right_hash,json=rightHash,proto3" json:"right_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerkleNodeHashes) Reset() {
	*x = MerkleNodeHashes{}
	mi := &file_spore_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerkleNodeHashes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerkleNodeHashes) ProtoMessage() {}

func (x *MerkleNodeHashes) ProtoReflect() protoreflect.Message {
	mi := &file_spore_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerkleNodeHashes.ProtoReflect.Descriptor instead.
func (*MerkleNodeHashes) Descriptor() ([]byte, []int) {
	return file_spore_proto_rawDescGZIP(), []int{16}
}

func (x *MerkleNodeHashes) GetLeftHash() []byte {
	if x != nil {
		return x.LeftHash
	}
	return nil
}

func (x *MerkleNodeHashes) GetRightHash() []byte {
	if x != nil {
		return x.RightHash
	}
	return nil
}

type MerkleChildrenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*MerkleNodeHashes    `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"` // same order as request paths
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerkleChildrenResponse) Reset() {
	*x = MerkleChildrenResponse{}
	mi := &file_spore_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerkleChildrenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerkleChildrenResponse) ProtoMessage() {}

func (x *MerkleChildrenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spore_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerkleChildrenResponse.ProtoReflect.Descriptor instead.
func (*MerkleChildrenResponse) Descriptor() ([]byte, []int) {
	return file_spore_proto_rawDescGZIP(), []int{17}
}

func (x *MerkleChildrenResponse) GetNodes() []*MerkleNodeHashes {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type MerkleLeafRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tree          TreeKind               `protobuf:"varint,1,opt,name=tree,proto3,enum=spore.TreeKind" json:"tree,omitempty"`
	GroupPrefixes []uint32               `protobuf:"varint,2,rep,packed,name=group_prefixes,json=groupPrefixes,proto3" json:"group_prefixes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerkleLeafRequest) Reset() {
	*x = MerkleLeafRequest{}
	mi := &file_spore_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerkleLeafRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerkleLeafRequest) ProtoMessage() {}

func (x *MerkleLeafRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spore_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerkleLeafRequest.ProtoReflect.Descriptor instead.
func (*MerkleLeafRequest) Descriptor() ([]byte, []int) {
	return file_spore_proto_rawDescGZIP(), []int{18}
}

func (x *MerkleLeafRequest) GetTree() TreeKind {
	if x != nil {
		return x.Tree
	}
	return TreeKind_DATA
}

func (x *MerkleLeafRequest) GetGroupPrefixes() []uint32 {
	if x != nil {
		return x.GroupPrefixes
	}
	return nil
}

type MerkleLeafGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupPrefix   uint32                 `protobuf:"varint,1,opt,name=group_prefix,json=groupPrefix,proto3" json:"group_prefix,omitempty"`
	ObjectIds     [][]byte               `protobuf:"bytes,2,rep,name=object_ids,json=objectIds,proto3" json:"object_ids,omitempty"` // sorted
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerkleLeafGroup) Reset() {
	*x = MerkleLeafGroup{}
	mi := &file_spore_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerkleLeafGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerkleLeafGroup) ProtoMessage() {}

func (x *MerkleLeafGroup) ProtoReflect() protoreflect.Message {
	mi := &file_spore_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerkleLeafGroup.ProtoReflect.Descriptor instead.
func (*MerkleLeafGroup) Descriptor() ([]byte, []int) {
	return file_spore_proto_rawDescGZIP(), []int{19}
}

func (x *MerkleLeafGroup) GetGroupPrefix() uint32 {
	if x != nil {
		return x.GroupPrefix
	}
	return 0
}

func (x *MerkleLeafGroup) GetObjectIds() [][]byte {
	if x != nil {
		return x.ObjectIds
	}
	return nil
}

type MerkleLeafResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        []*MerkleLeafGroup     `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerkleLeafResponse) Reset() {
	*x = MerkleLeafResponse{}
	mi := &file_spore_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerkleLeafResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerkleLeafResponse) ProtoMessage() {}

func (x *MerkleLeafResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spore_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerkleLeafResponse.ProtoReflect.Descriptor instead.
func (*MerkleLeafResponse) Descriptor() ([]byte, []int) {
	return file_spore_proto_rawDescGZIP(), []int{20}
}

func (x *MerkleLeafResponse) GetGroups() []*MerkleLeafGroup {
	if x != nil {
		return x.Groups
	}
	return nil
}

type GetObjectsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tree          TreeKind               `protobuf:"varint,1,opt,name=tree,proto3,enum=spore.TreeKind" json:"tree,omitempty"`
	ObjectIds     [][]byte               `protobuf:"bytes,2,rep,name=object_ids,json=objectIds,proto3" json:"object_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetObjectsRequest) Reset() {
	*x = GetObjectsRequest{}
	mi := &file_spore_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectsRequest) ProtoMessage() {}

func (x *GetObjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spore_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectsRequest.ProtoReflect.Descriptor instead.
func (*GetObjectsRequest) Descriptor() ([]byte, []int) {
	return file_spore_proto_rawDescGZIP(), []int{21}
}

func (x *GetObjectsRequest) GetTree() TreeKind {
	if x != nil {
		return x.Tree
	}
	return TreeKind_DATA
}

func (x *GetObjectsRequest) GetObjectIds() [][]byte {
	if x != nil {
		return x.ObjectIds
	}
	return nil
}

type GetObjectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Objects       []*StoredObject        `protobuf:"bytes,1,rep,name=objects,proto3" json:"objects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetObjectsResponse) Reset() {
	*x = GetObjectsResponse{}
	mi := &file_spore_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectsResponse) ProtoMessage() {}

func (x *GetObjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spore_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectsResponse.ProtoReflect.Descriptor instead.
func (*GetObjectsResponse) Descriptor() ([]byte, []int) {
	return file_spore_proto_rawDescGZIP(), []int{22}
}

func (x *GetObjectsResponse) GetObjects() []*StoredObject {
	if x != nil {
		return x.Objects
	}
	return nil
}

type CommandStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stored        int64                  `protobuf:"varint,1,opt,name=stored,proto3" json:"stored,omitempty"`
	Succeeded     int64                  `protobuf:"varint,2,opt,name=succeeded,proto3" json:"succeeded,omitempty"`
	Failed        int64                  `protobuf:"varint,3,opt,name=failed,proto3" json:"failed,omitempty"`
	ExecMsMax     int64                  `protobuf:"varint,4,opt,name=exec_ms_max,json=execMsMax,proto3" json:"exec_ms_max,omitempty"`
	ExecMsMin     int64                  `protobuf:"varint,5,opt,name=exec_ms_min,json=execMsMin,proto3" json:"exec_ms_min,omitempty"`
	ExecMsAvg     float64                `protobuf:"fixed64,6,opt,name=exec_ms_avg,json=execMsAvg,proto3" json:"exec_ms_avg,omitempty"`
	ExecMsMedian  int64                  `protobuf:"varint,7,opt,name=exec_ms_median,json=execMsMedian,proto3" json:"exec_ms_median,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandStats) Reset() {
	*x = CommandStats{}
	mi := &file_spore_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandStats) ProtoMessage() {}

func (x *CommandStats) ProtoReflect() protoreflect.Message {
	mi := &file_spore_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandStats.ProtoReflect.Descriptor instead.
func (*CommandStats) Descriptor() ([]byte, []int) {
	return file_spore_proto_rawDescGZIP(), []int{23}
}

func (x *CommandStats) GetStored() int64 {
	if x != nil {
		return x.Stored
	}
	return 0
}

func (x *CommandStats) GetSucceeded() int64 {
	if x != nil {
		return x.Succeeded
	}
	return 0
}

func (x *CommandStats) GetFailed() int64 {
	if x != nil {
		return x.Failed
	}
	return 0
}

func (x *CommandStats) GetExecMsMax() int64 {
	if x != nil {
		return x.ExecMsMax
	}
	return 0
}

func (x *CommandStats) GetExecMsMin() int64 {
	if x != nil {
		return x.ExecMsMin
	}
	return 0
}

func (x *CommandStats) GetExecMsAvg() float64 {
	if x != nil {
		return x.ExecMsAvg
	}
	return 0
}

func (x *CommandStats) GetExecMsMedian() int64 {
	if x != nil {
		return x.ExecMsMedian
	}
	return 0
}

type StorageStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectCount   int64                  `protobuf:"varint,1,opt,name=object_count,json=objectCount,proto3" json:"object_count,omitempty"`
	TotalBytes    int64                  `protobuf:"varint,2,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	FileSizeMax   int64                  `protobuf:"varint,3,opt,name=file_size_max,json=fileSizeMax,proto3" json:"file_size_max,omitempty"`
	FileSizeMin   int64                  `protobuf:"varint,4,opt,name=file_size_min,json=fileSizeMin,proto3" json:"file_size_min,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageStats) Reset() {
	*x = StorageStats{}
	mi := &file_spore_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageStats) ProtoMessage() {}

func (x *StorageStats) ProtoReflect() protoreflect.Message {
	mi := &file_spore_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageStats.ProtoReflect.Descriptor instead.
func (*StorageStats) Descriptor() ([]byte, []int) {
	return file_spore_proto_rawDescGZIP(), []int{24}
}

func (x *StorageStats) GetObjectCount() int64 {
	if x != nil {
		return x.ObjectCount
	}
	return 0
}

func (x *StorageStats) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *StorageStats) GetFileSizeMax() int64 {
	if x != nil {
		return x.FileSizeMax
	}
	return 0
}

func (x *StorageStats) GetFileSizeMin() int64 {
	if x != nil {
		return x.FileSizeMin
	}
	return 0
}

type MerkleSyncStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rounds        int64                  `protobuf:"varint,1,opt,name=rounds,proto3" json:"rounds,omitempty"`
	ObjectsSynced int64                  `protobuf:"varint,2,opt,name=objects_synced,json=objectsSynced,proto3" json:"objects_synced,omitempty"`
	BytesSynced   int64                  `protobuf:"varint,3,opt,name=bytes_synced,json=bytesSynced,proto3" json:"bytes_synced,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerkleSyncStats) Reset() {
	*x = MerkleSyncStats{}
	mi := &file_spore_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerkleSyncStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerkleSyncStats) ProtoMessage() {}

func (x *MerkleSyncStats) ProtoReflect() protoreflect.Message {
	mi := &file_spore_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerkleSyncStats.ProtoReflect.Descriptor instead.
func (*MerkleSyncStats) Descriptor() ([]byte, []int) {
	return file_spore_proto_rawDescGZIP(), []int{25}
}

func (x *MerkleSyncStats) GetRounds() int64 {
	if x != nil {
		return x.Rounds
	}
	return 0
}

func (x *MerkleSyncStats) GetObjectsSynced() int64 {
	if x != nil {
		return x.ObjectsSynced
	}
	return 0
}

func (x *MerkleSyncStats) GetBytesSynced() int64 {
	if x != nil {
		return x.BytesSynced
	}
	return 0
}

type MetricsSnapshot struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NodeId         string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	TimestampUnix  int64                  `protobuf:"varint,2,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	CreatedAtUtc   string                 `protobuf:"bytes,3,opt,name=created_at_utc,json=createdAtUtc,proto3" json:"created_at_utc,omitempty"`
	ParentId       string                 `protobuf:"bytes,4,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"` // empty for a node started directly by Primogenitor
	CpuPercent     float64                `protobuf:"fixed64,5,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemoryRssBytes int64                  `protobuf:"varint,6,opt,name=memory_rss_bytes,json=memoryRssBytes,proto3" json:"memory_rss_bytes,omitempty"`
	Goroutines     int64                  `protobuf:"varint,7,opt,name=goroutines,proto3" json:"goroutines,omitempty"`
	MembersAlive   int64                  `protobuf:"varint,8,opt,name=members_alive,json=membersAlive,proto3" json:"members_alive,omitempty"`
	MembersSuspect int64                  `protobuf:"varint,9,opt,name=members_suspect,json=membersSuspect,proto3" json:"members_suspect,omitempty"`
	MembersDead    int64                  `protobuf:"varint,10,opt,name=members_dead,json=membersDead,proto3" json:"members_dead,omitempty"`
	Commands       *CommandStats          `protobuf:"bytes,11,opt,name=commands,proto3" json:"commands,omitempty"`
	Storage        *StorageStats          `protobuf:"bytes,12,opt,name=storage,proto3" json:"storage,omitempty"`
	MerkleSync     *MerkleSyncStats       `protobuf:"bytes,13,opt,name=merkle_sync,json=merkleSync,proto3" json:"merkle_sync,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MetricsSnapshot) Reset() {
	*x = MetricsSnapshot{}
	mi := &file_spore_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsSnapshot) ProtoMessage() {}

func (x *MetricsSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_spore_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsSnapshot.ProtoReflect.Descriptor instead.
func (*MetricsSnapshot) Descriptor() ([]byte, []int) {
	return file_spore_proto_rawDescGZIP(), []int{26}
}

func (x *MetricsSnapshot) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *MetricsSnapshot) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

func (x *MetricsSnapshot) GetCreatedAtUtc() string {
	if x != nil {
		return x.CreatedAtUtc
	}
	return ""
}

func (x *MetricsSnapshot) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *MetricsSnapshot) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *MetricsSnapshot) GetMemoryRssBytes() int64 {
	if x != nil {
		return x.MemoryRssBytes
	}
	return 0
}

func (x *MetricsSnapshot) GetGoroutines() int64 {
	if x != nil {
		return x.Goroutines
	}
	return 0
}

func (x *MetricsSnapshot) GetMembersAlive() int64 {
	if x != nil {
		return x.MembersAlive
	}
	return 0
}

func (x *MetricsSnapshot) GetMembersSuspect() int64 {
	if x != nil {
		return x.MembersSuspect
	}
	return 0
}

func (x *MetricsSnapshot) GetMembersDead() int64 {
	if x != nil {
		return x.MembersDead
	}
	return 0
}

func (x *MetricsSnapshot) GetCommands() *CommandStats {
	if x != nil {
		return x.Commands
	}
	return nil
}

func (x *MetricsSnapshot) GetStorage() *StorageStats {
	if x != nil {
		return x.Storage
	}
	return nil
}

func (x *MetricsSnapshot) GetMerkleSync() *MerkleSyncStats {
	if x != nil {
		return x.MerkleSync
	}
	return nil
}

var File_spore_proto protoreflect.FileDescriptor

const file_spore_proto_rawDesc = "" +
	"\n" +
	"\vspore.proto\x12\x05spore\"\x8a\x02\n" +
	"\n" +
	"SpawnRules\x120\n" +
	"\x14max_generation_depth\x18\x01 \x01(\x05R\x12maxGenerationDepth\x124\n" +
	"\x16spawn_interval_seconds\x18\x02 \x01(\x05R\x14spawnIntervalSeconds\x12/\n" +
	"\n" +
	"spawn_mode\x18\x03 \x01(\x0e2\x10.spore.SpawnModeR\tspawnMode\x123\n" +
	"\x16max_children_per_batch\x18\x04 \x01(\x05R\x13maxChildrenPerBatch\x12.\n" +
	"\x13batch_pause_seconds\x18\x05 \x01(\x05R\x11batchPauseSeconds\"\xc9\x01\n" +
	"\aGenesis\x12\x1d\n" +
	"\n" +
	"network_id\x18\x01 \x01(\tR\tnetworkId\x12(\n" +
	"\x10owner_public_key\x18\x02 \x01(\fR\x0eownerPublicKey\x12A\n" +
	"\x1dmetrics_encryption_public_key\x18\x03 \x01(\fR\x1ametricsEncryptionPublicKey\x122\n" +
	"\vspawn_rules\x18\x04 \x01(\v2\x11.spore.SpawnRulesR\n" +
	"spawnRules\",\n" +
	"\aCommand\x12!\n" +
	"\fbash_command\x18\x01 \x01(\tR\vbashCommand\"p\n" +
	"\x11SubmitDataRequest\x12#\n" +
	"\x04type\x18\x01 \x01(\x0e2\x0f.spore.DataTypeR\x04type\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\"D\n" +
	"\tSubmitAck\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x1b\n" +
	"\tobject_id\x18\x02 \x01(\fR\bobjectId\"k\n" +
	"\fStoredObject\x12#\n" +
	"\x04type\x18\x01 \x01(\x0e2\x0f.spore.DataTypeR\x04type\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\"0\n" +
	"\x10TerminateRequest\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\fR\tsignature\"*\n" +
	"\fTerminateAck\x12\x1a\n" +
	"\breceived\x18\x01 \x01(\bR\breceived\"v\n" +
	"\vMemberState\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12+\n" +
	"\x06status\x18\x02 \x01(\x0e2\x13.spore.MemberStatusR\x06status\x12 \n" +
	"\vincarnation\x18\x03 \x01(\x03R\vincarnation\"b\n" +
	"\vPingRequest\x12!\n" +
	"\ffrom_address\x18\x01 \x01(\tR\vfromAddress\x120\n" +
	"\tpiggyback\x18\x02 \x03(\v2\x12.spore.MemberStateR\tpiggyback\"@\n" +
	"\fPingResponse\x120\n" +
	"\tpiggyback\x18\x02 \x03(\v2\x12.spore.MemberStateR\tpiggyback\"<\n" +
	"\x13IndirectPingRequest\x12%\n" +
	"\x0etarget_address\x18\x01 \x01(\tR\rtargetAddress\",\n" +
	"\x14IndirectPingResponse\x12\x14\n" +
	"\x05acked\x18\x01 \x01(\bR\x05acked\"\x83\x01\n" +
	"\x0eGossipExchange\x12$\n" +
	"\x0edata_root_hash\x18\x01 \x01(\fR\fdataRootHash\x12*\n" +
	"\x11metrics_root_hash\x18\x02 \x01(\fR\x0fmetricsRootHash\x12\x1f\n" +
	"\vknown_peers\x18\x03 \x03(\tR\n" +
	"knownPeers\"C\n" +
	"\n" +
	"MerklePath\x12\x14\n" +
	"\x05depth\x18\x01 \x01(\rR\x05depth\x12\x1f\n" +
	"\vprefix_bits\x18\x02 \x01(\rR\n" +
	"prefixBits\"e\n" +
	"\x15MerkleChildrenRequest\x12#\n" +
	"\x04tree\x18\x01 \x01(\x0e2\x0f.spore.TreeKindR\x04tree\x12'\n" +
	"\x05paths\x18\x02 \x03(\v2\x11.spore.MerklePathR\x05paths\"N\n" +
	"\x10MerkleNodeHashes\x12\x1b\n" +
	"\tleft_hash\x18\x01 \x01(\fR\bleftHash\x12\x1d\n" +
	"\n" +
	"right_hash\x18\x02 \x01(\fR\trightHash\"G\n" +
	"\x16MerkleChildrenResponse\x12-\n" +
	"\x05nodes\x18\x01 \x03(\v2\x17.spore.MerkleNodeHashesR\x05nodes\"_\n" +
	"\x11MerkleLeafRequest\x12#\n" +
	"\x04tree\x18\x01 \x01(\x0e2\x0f.spore.TreeKindR\x04tree\x12%\n" +
	"\x0egroup_prefixes\x18\x02 \x03(\rR\rgroupPrefixes\"S\n" +
	"\x0fMerkleLeafGroup\x12!\n" +
	"\fgroup_prefix\x18\x01 \x01(\rR\vgroupPrefix\x12\x1d\n" +
	"\n" +
	"object_ids\x18\x02 \x03(\fR\tobjectIds\"D\n" +
	"\x12MerkleLeafResponse\x12.\n" +
	"\x06groups\x18\x01 \x03(\v2\x16.spore.MerkleLeafGroupR\x06groups\"W\n" +
	"\x11GetObjectsRequest\x12#\n" +
	"\x04tree\x18\x01 \x01(\x0e2\x0f.spore.TreeKindR\x04tree\x12\x1d\n" +
	"\n" +
	"object_ids\x18\x02 \x03(\fR\tobjectIds\"C\n" +
	"\x12GetObjectsResponse\x12-\n" +
	"\aobjects\x18\x01 \x03(\v2\x13.spore.StoredObjectR\aobjects\"\xe2\x01\n" +
	"\fCommandStats\x12\x16\n" +
	"\x06stored\x18\x01 \x01(\x03R\x06stored\x12\x1c\n" +
	"\tsucceeded\x18\x02 \x01(\x03R\tsucceeded\x12\x16\n" +
	"\x06failed\x18\x03 \x01(\x03R\x06failed\x12\x1e\n" +
	"\vexec_ms_max\x18\x04 \x01(\x03R\texecMsMax\x12\x1e\n" +
	"\vexec_ms_min\x18\x05 \x01(\x03R\texecMsMin\x12\x1e\n" +
	"\vexec_ms_avg\x18\x06 \x01(\x01R\texecMsAvg\x12$\n" +
	"\x0eexec_ms_median\x18\a \x01(\x03R\fexecMsMedian\"\x9a\x01\n" +
	"\fStorageStats\x12!\n" +
	"\fobject_count\x18\x01 \x01(\x03R\vobjectCount\x12\x1f\n" +
	"\vtotal_bytes\x18\x02 \x01(\x03R\n" +
	"totalBytes\x12\"\n" +
	"\rfile_size_max\x18\x03 \x01(\x03R\vfileSizeMax\x12\"\n" +
	"\rfile_size_min\x18\x04 \x01(\x03R\vfileSizeMin\"s\n" +
	"\x0fMerkleSyncStats\x12\x16\n" +
	"\x06rounds\x18\x01 \x01(\x03R\x06rounds\x12%\n" +
	"\x0eobjects_synced\x18\x02 \x01(\x03R\robjectsSynced\x12!\n" +
	"\fbytes_synced\x18\x03 \x01(\x03R\vbytesSynced\"\x89\x04\n" +
	"\x0fMetricsSnapshot\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12%\n" +
	"\x0etimestamp_unix\x18\x02 \x01(\x03R\rtimestampUnix\x12$\n" +
	"\x0ecreated_at_utc\x18\x03 \x01(\tR\fcreatedAtUtc\x12\x1b\n" +
	"\tparent_id\x18\x04 \x01(\tR\bparentId\x12\x1f\n" +
	"\vcpu_percent\x18\x05 \x01(\x01R\n" +
	"cpuPercent\x12(\n" +
	"\x10memory_rss_bytes\x18\x06 \x01(\x03R\x0ememoryRssBytes\x12\x1e\n" +
	"\n" +
	"goroutines\x18\a \x01(\x03R\n" +
	"goroutines\x12#\n" +
	"\rmembers_alive\x18\b \x01(\x03R\fmembersAlive\x12'\n" +
	"\x0fmembers_suspect\x18\t \x01(\x03R\x0emembersSuspect\x12!\n" +
	"\fmembers_dead\x18\n" +
	" \x01(\x03R\vmembersDead\x12/\n" +
	"\bcommands\x18\v \x01(\v2\x13.spore.CommandStatsR\bcommands\x12-\n" +
	"\astorage\x18\f \x01(\v2\x13.spore.StorageStatsR\astorage\x127\n" +
	"\vmerkle_sync\x18\r \x01(\v2\x16.spore.MerkleSyncStatsR\n" +
	"merkleSync*$\n" +
	"\tSpawnMode\x12\v\n" +
	"\aPROCESS\x10\x00\x12\n" +
	"\n" +
	"\x06DOCKER\x10\x01*!\n" +
	"\bDataType\x12\b\n" +
	"\x04FILE\x10\x00\x12\v\n" +
	"\aCOMMAND\x10\x01*0\n" +
	"\fMemberStatus\x12\t\n" +
	"\x05ALIVE\x10\x00\x12\v\n" +
	"\aSUSPECT\x10\x01\x12\b\n" +
	"\x04DEAD\x10\x02*!\n" +
	"\bTreeKind\x12\b\n" +
	"\x04DATA\x10\x00\x12\v\n" +
	"\aMETRICS\x10\x012\x94\x04\n" +
	"\vNodeService\x128\n" +
	"\n" +
	"SubmitData\x12\x18.spore.SubmitDataRequest\x1a\x10.spore.SubmitAck\x12?\n" +
	"\x0fSubmitTerminate\x12\x17.spore.TerminateRequest\x1a\x13.spore.TerminateAck\x12/\n" +
	"\x04Ping\x12\x12.spore.PingRequest\x1a\x13.spore.PingResponse\x12G\n" +
	"\fPingIndirect\x12\x1a.spore.IndirectPingRequest\x1a\x1b.spore.IndirectPingResponse\x12;\n" +
	"\vGossipRound\x12\x15.spore.GossipExchange\x1a\x15.spore.GossipExchange\x12M\n" +
	"\x0eMerkleChildren\x12\x1c.spore.MerkleChildrenRequest\x1a\x1d.spore.MerkleChildrenResponse\x12A\n" +
	"\n" +
	"MerkleLeaf\x12\x18.spore.MerkleLeafRequest\x1a\x19.spore.MerkleLeafResponse\x12A\n" +
	"\n" +
	"GetObjects\x12\x18.spore.GetObjectsRequest\x1a\x19.spore.GetObjectsResponseB\x1fZ\x1dsporemachine/internal/sporepbb\x06proto3"

var (
	file_spore_proto_rawDescOnce sync.Once
	file_spore_proto_rawDescData []byte
)

func file_spore_proto_rawDescGZIP() []byte {
	file_spore_proto_rawDescOnce.Do(func() {
		file_spore_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spore_proto_rawDesc), len(file_spore_proto_rawDesc)))
	})
	return file_spore_proto_rawDescData
}

var file_spore_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_spore_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_spore_proto_goTypes = []any{
	(SpawnMode)(0),                 // 0: spore.SpawnMode
	(DataType)(0),                  // 1: spore.DataType
	(MemberStatus)(0),              // 2: spore.MemberStatus
	(TreeKind)(0),                  // 3: spore.TreeKind
	(*SpawnRules)(nil),             // 4: spore.SpawnRules
	(*Genesis)(nil),                // 5: spore.Genesis
	(*Command)(nil),                // 6: spore.Command
	(*SubmitDataRequest)(nil),      // 7: spore.SubmitDataRequest
	(*SubmitAck)(nil),              // 8: spore.SubmitAck
	(*StoredObject)(nil),           // 9: spore.StoredObject
	(*TerminateRequest)(nil),       // 10: spore.TerminateRequest
	(*TerminateAck)(nil),           // 11: spore.TerminateAck
	(*MemberState)(nil),            // 12: spore.MemberState
	(*PingRequest)(nil),            // 13: spore.PingRequest
	(*PingResponse)(nil),           // 14: spore.PingResponse
	(*IndirectPingRequest)(nil),    // 15: spore.IndirectPingRequest
	(*IndirectPingResponse)(nil),   // 16: spore.IndirectPingResponse
	(*GossipExchange)(nil),         // 17: spore.GossipExchange
	(*MerklePath)(nil),             // 18: spore.MerklePath
	(*MerkleChildrenRequest)(nil),  // 19: spore.MerkleChildrenRequest
	(*MerkleNodeHashes)(nil),       // 20: spore.MerkleNodeHashes
	(*MerkleChildrenResponse)(nil), // 21: spore.MerkleChildrenResponse
	(*MerkleLeafRequest)(nil),      // 22: spore.MerkleLeafRequest
	(*MerkleLeafGroup)(nil),        // 23: spore.MerkleLeafGroup
	(*MerkleLeafResponse)(nil),     // 24: spore.MerkleLeafResponse
	(*GetObjectsRequest)(nil),      // 25: spore.GetObjectsRequest
	(*GetObjectsResponse)(nil),     // 26: spore.GetObjectsResponse
	(*CommandStats)(nil),           // 27: spore.CommandStats
	(*StorageStats)(nil),           // 28: spore.StorageStats
	(*MerkleSyncStats)(nil),        // 29: spore.MerkleSyncStats
	(*MetricsSnapshot)(nil),        // 30: spore.MetricsSnapshot
}
var file_spore_proto_depIdxs = []int32{
	0,  // 0: spore.SpawnRules.spawn_mode:type_name -> spore.SpawnMode
	4,  // 1: spore.Genesis.spawn_rules:type_name -> spore.SpawnRules
	1,  // 2: spore.SubmitDataRequest.type:type_name -> spore.DataType
	1,  // 3: spore.StoredObject.type:type_name -> spore.DataType
	2,  // 4: spore.MemberState.status:type_name -> spore.MemberStatus
	12, // 5: spore.PingRequest.piggyback:type_name -> spore.MemberState
	12, // 6: spore.PingResponse.piggyback:type_name -> spore.MemberState
	3,  // 7: spore.MerkleChildrenRequest.tree:type_name -> spore.TreeKind
	18, // 8: spore.MerkleChildrenRequest.paths:type_name -> spore.MerklePath
	20, // 9: spore.MerkleChildrenResponse.nodes:type_name -> spore.MerkleNodeHashes
	3,  // 10: spore.MerkleLeafRequest.tree:type_name -> spore.TreeKind
	23, // 11: spore.MerkleLeafResponse.groups:type_name -> spore.MerkleLeafGroup
	3,  // 12: spore.GetObjectsRequest.tree:type_name -> spore.TreeKind
	9,  // 13: spore.GetObjectsResponse.objects:type_name -> spore.StoredObject
	27, // 14: spore.MetricsSnapshot.commands:type_name -> spore.CommandStats
	28, // 15: spore.MetricsSnapshot.storage:type_name -> spore.StorageStats
	29, // 16: spore.MetricsSnapshot.merkle_sync:type_name -> spore.MerkleSyncStats
	7,  // 17: spore.NodeService.SubmitData:input_type -> spore.SubmitDataRequest
	10, // 18: spore.NodeService.SubmitTerminate:input_type -> spore.TerminateRequest
	13, // 19: spore.NodeService.Ping:input_type -> spore.PingRequest
	15, // 20: spore.NodeService.PingIndirect:input_type -> spore.IndirectPingRequest
	17, // 21: spore.NodeService.GossipRound:input_type -> spore.GossipExchange
	19, // 22: spore.NodeService.MerkleChildren:input_type -> spore.MerkleChildrenRequest
	22, // 23: spore.NodeService.MerkleLeaf:input_type -> spore.MerkleLeafRequest
	25, // 24: spore.NodeService.GetObjects:input_type -> spore.GetObjectsRequest
	8,  // 25: spore.NodeService.SubmitData:output_type -> spore.SubmitAck
	11, // 26: spore.NodeService.SubmitTerminate:output_type -> spore.TerminateAck
	14, // 27: spore.NodeService.Ping:output_type -> spore.PingResponse
	16, // 28: spore.NodeService.PingIndirect:output_type -> spore.IndirectPingResponse
	17, // 29: spore.NodeService.GossipRound:output_type -> spore.GossipExchange
	21, // 30: spore.NodeService.MerkleChildren:output_type -> spore.MerkleChildrenResponse
	24, // 31: spore.NodeService.MerkleLeaf:output_type -> spore.MerkleLeafResponse
	26, // 32: spore.NodeService.GetObjects:output_type -> spore.GetObjectsResponse
	25, // [25:33] is the sub-list for method output_type
	17, // [17:25] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_spore_proto_init() }
func file_spore_proto_init() {
	if File_spore_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spore_proto_rawDesc), len(file_spore_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_spore_proto_goTypes,
		DependencyIndexes: file_spore_proto_depIdxs,
		EnumInfos:         file_spore_proto_enumTypes,
		MessageInfos:      file_spore_proto_msgTypes,
	}.Build()
	File_spore_proto = out.File
	file_spore_proto_goTypes = nil
	file_spore_proto_depIdxs = nil
}
